---
title: "pivot_lobsters.Rmd"
author: "Jeremy Lang"
date: "1/27/2020"
output: html_document
---

```{r}

## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')

## read in data
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)

skimr::skim(lobsters)

```

```{r}

# populate our variable
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_mm = sd(size_mm, na.rm = TRUE)
  )

# inspect our variable
siteyear_summary %>% kable()
```


There are `r nrow(lobsters)` total lobsters included in this report.

## Median Lobster Size for each site year

```{r}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(median_size_mm = median(size_mm, na.rm = TRUE))

ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
         geom_line()

ggsave(here("figures", "lobsters-line.png"))

```

```{r}

ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)

ggsave(here("figures", "lobsters-cols.png"))

```

```{r}

lobsters %>%
  count(site, year)

```

There are `r count(lobsters)` total lobsters included in this summary.



